// This file is generated by ATC.

#include "demo.h"

int exec_local_get(struct wst st, int sp, int x) {
    unsigned int val = st.loc[x];
    st.op[sp] = val;
    sp = sp + 1;
    return sp;
}

int exec_local_set(struct wst st, int sp, int x) {
    int idx = sp - 1;
    unsigned int val = st.op[idx];
    st.loc[x] = val;
    sp = idx;
    return sp;
}
