// This file is generated by ATC.

struct wst {
    unsigned int op[64];
    unsigned int loc[16];
};

int exec_local_get(struct wst st, int sp, int x);

int exec_local_set(struct wst st, int sp, int x);
