// This file is generated by ATC.

#include "run.h"

unsigned char wasm_buf[65536];

int check_magic(void) {
    return (int) wasm_buf[0] == 0 && (int) wasm_buf[1] == 97 && (int) wasm_buf[2] == 115 && (int) wasm_buf[3] == 109;
}

void parse_module(struct wmod *m) {
    int ok = check_magic();
    if (ok) {
        int cursor = 8;
        int fuel = 16;
        while (fuel > 0) {
            int id = (int) wasm_buf[cursor];
            int size = (int) wasm_buf[cursor + 1];
            int next = cursor + (size + 2);
            int safe = next <= 60000;
            if (safe && id == 7) {
                int name_len = (int) wasm_buf[cursor + 3];
                int name_off = cursor + 4;
                m->export_off = name_off;
                m->export_len = (unsigned char) name_len;
            }
            if (safe && id == 10) {
                int body_size = (int) wasm_buf[cursor + 3];
                int ng = (int) wasm_buf[cursor + 4];
                if (ng == 0) {
                    int body_off = cursor + 5;
                    int body_len = body_size - 1;
                    m->body_off = body_off;
                    m->body_len = body_len;
                    m->num_locals = (unsigned char) 0;
                } else {
                    if (ng == 1) {
                        int nloc = (int) wasm_buf[cursor + 5];
                        int body_off = cursor + 7;
                        int body_len = body_size - 3;
                        m->body_off = body_off;
                        m->body_len = body_len;
                        m->num_locals = (unsigned char) nloc;
                    } else {
                        m->err = (unsigned char) 2;
                    }
                }
            }
            cursor = safe ? next : cursor;
            fuel = safe ? fuel - 1 : 0;
        }
    } else {
        m->err = (unsigned char) 1;
    }
}

unsigned int run_wasm_gen(struct wst *st, struct wmod *m, unsigned int a, unsigned int b) {
    st->loc[0] = a;
    st->loc[1] = b;
    int pc_raw = m->body_off;
    int pc = pc_raw >= 0 && pc_raw <= 60000 ? pc_raw : 0;
    int sp = 0;
    int nl = 0;
    int halted = 0;
    int fuel = 100000;
    while (halted == 0 && fuel > 0 && pc < 59998) {
        int b = (int) wasm_buf[pc];
        if (b == 11) {
            halted = 1;
            fuel = fuel - 1;
        } else {
            if (b == 26) {
                int ok = sp > 0;
                sp = ok ? sp - 1 : sp;
                pc = pc + 1;
                halted = ok ? halted : 1;
                fuel = fuel - 1;
            } else {
                if (b == 32) {
                    int x = (int) wasm_buf[pc + 1];
                    int ok = sp < 64 && x < 16;
                    int x_safe = ok ? x : 0;
                    int sp_safe = ok ? sp : 0;
                    unsigned int v = st->loc[x_safe];
                    st->op[sp_safe] = v;
                    sp = ok ? sp + 1 : sp;
                    pc = pc + 2;
                    halted = ok ? halted : 1;
                    fuel = fuel - 1;
                } else {
                    if (b == 33) {
                        int x = (int) wasm_buf[pc + 1];
                        int ok = sp > 0 && x < 16;
                        int x_safe = ok ? x : 0;
                        int idx = ok ? sp - 1 : 0;
                        unsigned int v = st->op[idx];
                        st->loc[x_safe] = v;
                        sp = ok ? sp - 1 : sp;
                        pc = pc + 2;
                        halted = ok ? halted : 1;
                        fuel = fuel - 1;
                    } else {
                        if (b == 34) {
                            int x = (int) wasm_buf[pc + 1];
                            int ok = sp > 0 && x < 16;
                            int x_safe = ok ? x : 0;
                            int idx = ok ? sp - 1 : 0;
                            unsigned int v = st->op[idx];
                            st->loc[x_safe] = v;
                            pc = pc + 2;
                            halted = ok ? halted : 1;
                            fuel = fuel - 1;
                        } else {
                            if (b == 65) {
                                int n = (int) wasm_buf[pc + 1];
                                int ok = sp < 64;
                                int sp_safe = ok ? sp : 0;
                                unsigned int nv = (unsigned int) n;
                                st->op[sp_safe] = nv;
                                sp = ok ? sp + 1 : sp;
                                pc = pc + 2;
                                halted = ok ? halted : 1;
                                fuel = fuel - 1;
                            } else {
                                if (b == 106) {
                                    int ok = sp > 1;
                                    int bi = ok ? sp - 1 : 0;
                                    int ai = ok ? sp - 2 : 0;
                                    unsigned int bv = st->op[bi];
                                    unsigned int av = st->op[ai];
                                    unsigned int rv = av + bv;
                                    st->op[ai] = rv;
                                    sp = ok ? sp - 1 : sp;
                                    pc = pc + 1;
                                    halted = ok ? halted : 1;
                                    fuel = fuel - 1;
                                } else {
                                    if (b == 112) {
                                        int ok = sp > 1;
                                        int bi = ok ? sp - 1 : 0;
                                        int ai = ok ? sp - 2 : 0;
                                        unsigned int bv = st->op[bi];
                                        unsigned int av = st->op[ai];
                                        int nz = bv != 0U;
                                        int safe = ok && nz;
                                        unsigned int bv_safe = safe ? bv : 1U;
                                        unsigned int rv = av % bv_safe;
                                        st->op[ai] = rv;
                                        sp = safe ? sp - 1 : sp;
                                        pc = pc + 1;
                                        halted = safe ? halted : 1;
                                        fuel = fuel - 1;
                                    } else {
                                        halted = 1;
                                        fuel = fuel - 1;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    return st->op[0];
}
