// This file is generated by ATC.

#include "loop-demo.h"

unsigned char wasm_buf[65536];

void exec_run(struct wst *st, int pc) {
    int sp = 0;
    int nl = 0;
    int halted = 0;
    int fuel = 100000;
    while (halted == 0 && fuel > 0 && pc < 59998) {
        int b = (int) wasm_buf[pc];
        if (b == 11) {
            halted = 1;
            fuel = fuel - 1;
        } else {
            if (b == 26) {
                int ok = sp > 0;
                sp = ok ? sp - 1 : sp;
                pc = pc + 1;
                halted = ok ? halted : 1;
                fuel = fuel - 1;
            } else {
                if (b == 32) {
                    int x = (int) wasm_buf[pc + 1];
                    int ok = sp < 64 && x < 16;
                    int x_safe = ok ? x : 0;
                    int sp_safe = ok ? sp : 0;
                    unsigned int v = st->loc[x_safe];
                    st->op[sp_safe] = v;
                    sp = ok ? sp + 1 : sp;
                    pc = pc + 2;
                    halted = ok ? halted : 1;
                    fuel = fuel - 1;
                } else {
                    if (b == 33) {
                        int x = (int) wasm_buf[pc + 1];
                        int ok = sp > 0 && x < 16;
                        int x_safe = ok ? x : 0;
                        int idx = ok ? sp - 1 : 0;
                        unsigned int v = st->op[idx];
                        st->loc[x_safe] = v;
                        sp = ok ? sp - 1 : sp;
                        pc = pc + 2;
                        halted = ok ? halted : 1;
                        fuel = fuel - 1;
                    } else {
                        if (b == 34) {
                            int x = (int) wasm_buf[pc + 1];
                            int ok = sp > 0 && x < 16;
                            int x_safe = ok ? x : 0;
                            int idx = ok ? sp - 1 : 0;
                            unsigned int v = st->op[idx];
                            st->loc[x_safe] = v;
                            pc = pc + 2;
                            halted = ok ? halted : 1;
                            fuel = fuel - 1;
                        } else {
                            if (b == 65) {
                                int n = (int) wasm_buf[pc + 1];
                                int ok = sp < 64;
                                int sp_safe = ok ? sp : 0;
                                unsigned int nv = (unsigned int) n;
                                st->op[sp_safe] = nv;
                                sp = ok ? sp + 1 : sp;
                                pc = pc + 2;
                                halted = ok ? halted : 1;
                                fuel = fuel - 1;
                            } else {
                                if (b == 106) {
                                    int ok = sp > 1;
                                    int bi = ok ? sp - 1 : 0;
                                    int ai = ok ? sp - 2 : 0;
                                    unsigned int bv = st->op[bi];
                                    unsigned int av = st->op[ai];
                                    unsigned int rv = av + bv;
                                    st->op[ai] = rv;
                                    sp = ok ? sp - 1 : sp;
                                    pc = pc + 1;
                                    halted = ok ? halted : 1;
                                    fuel = fuel - 1;
                                } else {
                                    if (b == 112) {
                                        int ok = sp > 1;
                                        int bi = ok ? sp - 1 : 0;
                                        int ai = ok ? sp - 2 : 0;
                                        unsigned int bv = st->op[bi];
                                        unsigned int av = st->op[ai];
                                        int nz = bv != 0U;
                                        int safe = ok && nz;
                                        unsigned int bv_safe = safe ? bv : 1U;
                                        unsigned int rv = av % bv_safe;
                                        st->op[ai] = rv;
                                        sp = safe ? sp - 1 : sp;
                                        pc = pc + 1;
                                        halted = safe ? halted : 1;
                                        fuel = fuel - 1;
                                    } else {
                                        halted = 1;
                                        fuel = fuel - 1;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
