// This file is generated by ATC.

extern unsigned char wasm_buf[65536];

struct wmod {
    unsigned char err;
    int body_off;
    int body_len;
    unsigned char num_params;
    unsigned char num_results;
    unsigned char num_locals;
    int export_off;
    unsigned char export_len;
};

struct wst {
    unsigned int op[64];
    unsigned int loc[16];
    int lpc[16];
    int lsp[16];
    unsigned char lkind[16];
};

int check_magic(void);

void parse_module(struct wmod *m);

struct wcfg {
    unsigned char err;
    int nbr;
    int opener_pc[64];
    unsigned char opener[64];
    int end_pc[64];
    int else_pc[64];
    int pend_top;
    int pend[16];
};

int scan_end(int pc);

void apply_open(int pc, int b, struct wcfg *w);

void apply_end(int pc, struct wcfg *w);

void apply_else(int pc, struct wcfg *w);

void extract_cfg(struct wcfg *w, struct wmod *m);

unsigned int invoke(struct wst *st, struct wmod *m, unsigned int a, unsigned int b);
