// This file is generated by ATC.

#include "wasm-vm2.h"

unsigned char wasm_buf[65536];

int check_magic(void) {
    return (int) wasm_buf[0] == 0 && (int) wasm_buf[1] == 97 && (int) wasm_buf[2] == 115 && (int) wasm_buf[3] == 109;
}

void parse_module(struct wmod *m) {
    int ok = check_magic();
    if (ok) {
        int cursor = 8;
        int fuel = 16;
        while (fuel > 0) {
            int id = (int) wasm_buf[cursor];
            int size = (int) wasm_buf[cursor + 1];
            int next = cursor + (size + 2);
            int safe = next <= 60000;
            if (safe && id == 7) {
                int name_len = (int) wasm_buf[cursor + 3];
                int name_off = cursor + 4;
                m->export_off = name_off;
                m->export_len = (unsigned char) name_len;
            }
            if (safe && id == 10) {
                int body_size = (int) wasm_buf[cursor + 3];
                int ng = (int) wasm_buf[cursor + 4];
                if (ng == 0) {
                    int body_off = cursor + 5;
                    int body_len = body_size - 1;
                    m->body_off = body_off;
                    m->body_len = body_len;
                    m->num_locals = (unsigned char) 0;
                } else {
                    if (ng == 1) {
                        int nloc = (int) wasm_buf[cursor + 5];
                        int body_off = cursor + 7;
                        int body_len = body_size - 3;
                        m->body_off = body_off;
                        m->body_len = body_len;
                        m->num_locals = (unsigned char) nloc;
                    } else {
                        m->err = (unsigned char) 2;
                    }
                }
            }
            cursor = safe ? next : cursor;
            fuel = safe ? fuel - 1 : 0;
        }
    } else {
        m->err = (unsigned char) 1;
    }
}

void apply_open(int pc, int b, struct wcfg *w) {
    int nbr_raw = w->nbr;
    int pt_raw = w->pend_top;
    int ok = nbr_raw >= 0 && nbr_raw < 64 && pt_raw >= 0 && pt_raw < 16;
    if (ok) {
        w->opener_pc[nbr_raw] = pc;
        w->opener[nbr_raw] = (unsigned char) b;
        w->pend[pt_raw] = nbr_raw;
        w->nbr = nbr_raw + 1;
        w->pend_top = pt_raw + 1;
    } else {
        w->err = (unsigned char) 1;
    }
}

void apply_end(int pc, struct wcfg *w) {
    int pt_raw = w->pend_top;
    int ok = pt_raw > 0 && pt_raw <= 16;
    if (ok) {
        int top_idx = pt_raw - 1;
        int peek_raw = w->pend[top_idx];
        int peek = peek_raw >= 0 && peek_raw < 64 ? peek_raw : 0;
        w->end_pc[peek] = pc + 1;
        w->pend_top = top_idx;
    } else {
        w->pend_top = pt_raw;
    }
}

void apply_else(int pc, struct wcfg *w) {
    int pt_raw = w->pend_top;
    int ok = pt_raw > 0 && pt_raw <= 16;
    if (ok) {
        int top_idx = pt_raw - 1;
        int peek_raw = w->pend[top_idx];
        int peek = peek_raw >= 0 && peek_raw < 64 ? peek_raw : 0;
        w->else_pc[peek] = pc + 1;
    } else {
        w->err = (unsigned char) 1;
    }
}

void extract_cfg(struct wcfg *w, struct wmod *m) {
    int body_off_raw = m->body_off;
    int body_len_raw = m->body_len;
    int safe = body_off_raw >= 0 && body_off_raw <= 60000 && body_len_raw >= 0 && body_len_raw <= 60000;
    int pc = safe ? body_off_raw : 0;
    int end_raw = safe ? body_off_raw + body_len_raw : 0;
    int end_pc = end_raw <= 60000 ? end_raw : 60000;
    while (pc < end_pc && pc < 59998) {
        int b = (int) wasm_buf[pc];
        int is_open = b == 2 || (b == 3 || b == 4);
        int is_end_op = b == 11;
        int is_else_op = b == 5;
        int is_wide = is_open || (is_else_op || (b == 12 || (b == 13 || (b == 32 || (b == 33 || (b == 34 || b == 65))))));
        if (is_open) {
            apply_open(pc, b, w);
        } else {
            if (is_end_op) {
                apply_end(pc, w);
            } else {
                if (is_else_op) {
                    apply_else(pc, w);
                }
            }
        }
        int step = is_wide ? 2 : 1;
        pc = pc + step;
    }
}

int wcfg_end_pc_at(int pc, struct wcfg *w) {
    int i = 0;
    int acc = 0;
    while (w->nbr >= 0 && w->nbr < 65 && i < w->nbr && i < 64) {
        int opc = w->opener_pc[i];
        acc = acc == 0 && opc == pc ? w->end_pc[i] : acc;
        i = i + 1;
    }
    return acc;
}

unsigned int invoke_v2(struct wst *st, struct wmod *m, unsigned int a, unsigned int b, struct wcfg *w) {
    st->loc[0] = a;
    st->loc[1] = b;
    extract_cfg(w, m);
    int pc_raw = m->body_off;
    int pc = pc_raw >= 0 && pc_raw <= 60000 ? pc_raw : 0;
    int sp = 0;
    int nl = 0;
    int halted = 0;
    int fuel = 100000;
    while (halted == 0 && fuel > 0 && pc < 59998) {
        int b = (int) wasm_buf[pc];
        if (b == 32) {
            int x = (int) wasm_buf[pc + 1];
            int ok = sp < 64 && x < 16;
            int x_safe = ok ? x : 0;
            int sp_safe = ok ? sp : 0;
            unsigned int v = st->loc[x_safe];
            st->op[sp_safe] = v;
            sp = ok ? sp + 1 : sp;
            pc = pc + 2;
            halted = ok ? halted : 1;
        } else {
            if (b == 33) {
                int x = (int) wasm_buf[pc + 1];
                int ok = sp > 0 && x < 16;
                int x_safe = ok ? x : 0;
                int idx = ok ? sp - 1 : 0;
                unsigned int v = st->op[idx];
                st->loc[x_safe] = v;
                sp = ok ? sp - 1 : sp;
                pc = pc + 2;
                halted = ok ? halted : 1;
            } else {
                if (b == 34) {
                    int x = (int) wasm_buf[pc + 1];
                    int ok = sp > 0 && x < 16;
                    int x_safe = ok ? x : 0;
                    int idx = ok ? sp - 1 : 0;
                    unsigned int v = st->op[idx];
                    st->loc[x_safe] = v;
                    pc = pc + 2;
                    halted = ok ? halted : 1;
                } else {
                    if (b == 69) {
                        int ok = sp > 0;
                        int idx = ok ? sp - 1 : 0;
                        unsigned int v = st->op[idx];
                        int is0 = v == 0U || v == 0U;
                        unsigned int new_v = (unsigned int) is0;
                        st->op[idx] = new_v;
                        pc = pc + 1;
                        halted = ok ? halted : 1;
                    } else {
                        if (b == 112) {
                            int ok = sp > 1;
                            int bi = ok ? sp - 1 : 0;
                            int ai = ok ? sp - 2 : 0;
                            unsigned int bv = st->op[bi];
                            unsigned int av = st->op[ai];
                            int nz = bv != 0U || bv != 0U;
                            int safe = ok && nz;
                            unsigned int bv_safe = safe ? bv : 1U;
                            unsigned int rv = av % bv_safe;
                            st->op[ai] = rv;
                            sp = safe ? sp - 1 : sp;
                            pc = pc + 1;
                            halted = safe ? halted : 1;
                        } else {
                            if (b == 2) {
                                int ok = nl < 16;
                                int nl_safe = ok ? nl : 0;
                                int end_pc_raw = wcfg_end_pc_at(pc, w);
                                int end_pc = end_pc_raw >= 0 && end_pc_raw <= 60000 ? end_pc_raw : 0;
                                st->lpc[nl_safe] = end_pc;
                                st->lsp[nl_safe] = sp;
                                st->lkind[nl_safe] = (unsigned char) 0;
                                nl = ok ? nl + 1 : nl;
                                pc = pc + 2;
                                halted = ok ? halted : 1;
                                fuel = fuel - 1;
                            } else {
                                if (b == 3) {
                                    int ok = nl < 16;
                                    int nl_safe = ok ? nl : 0;
                                    int loop_pc = pc + 2;
                                    st->lpc[nl_safe] = loop_pc;
                                    st->lsp[nl_safe] = sp;
                                    st->lkind[nl_safe] = (unsigned char) 1;
                                    nl = ok ? nl + 1 : nl;
                                    pc = loop_pc;
                                    halted = ok ? halted : 1;
                                    fuel = fuel - 1;
                                } else {
                                    if (b == 11) {
                                        if (nl == 0) {
                                            halted = 1;
                                            fuel = fuel - 1;
                                        } else {
                                            nl = nl - 1;
                                            pc = pc + 1;
                                            fuel = fuel - 1;
                                        }
                                    } else {
                                        int is_br = b == 12;
                                        int is_brif = b == 13;
                                        int is_brx = is_br || is_brif;
                                        if (is_brx) {
                                            int l_byte = (int) wasm_buf[pc + 1];
                                            int pop_ok = is_br || sp > 0;
                                            int sp_after_pop = is_brif ? sp > 0 ? sp - 1 : sp : sp;
                                            int peek_idx = sp > 0 ? sp - 1 : 0;
                                            unsigned int peek_v = st->op[peek_idx];
                                            int cond_true = peek_v != 0U || peek_v != 0U;
                                            int take = is_br || is_brif && cond_true;
                                            int l_ok = l_byte < nl;
                                            int target_idx = l_ok ? nl - 1 - l_byte : 0;
                                            int tpc_raw = st->lpc[target_idx];
                                            int tsp_raw = st->lsp[target_idx];
                                            unsigned char tkind_uc = st->lkind[target_idx];
                                            int tkind = (int) tkind_uc;
                                            int tpc_ok = tpc_raw >= 0 && tpc_raw <= 60000;
                                            int tsp_ok = tsp_raw >= 0 && tsp_raw <= 64;
                                            int all_ok = pop_ok && l_ok && tpc_ok && tsp_ok;
                                            int new_nl = all_ok && take ? tkind == 1 ? target_idx + 1 : target_idx : nl;
                                            int new_sp = all_ok && take ? tsp_raw : sp_after_pop;
                                            int new_pc = all_ok && take ? tpc_raw : pc + 2;
                                            sp = new_sp;
                                            nl = new_nl;
                                            pc = new_pc;
                                            halted = all_ok ? halted : 1;
                                            fuel = fuel - 1;
                                        } else {
                                            halted = 1;
                                            fuel = fuel - 1;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    return st->op[0];
}
