// This file is generated by ATC.

extern unsigned char wasm_buf[65536];

struct wmod {
    unsigned char err;
    int body_off;
    int body_len;
    unsigned char num_params;
    unsigned char num_results;
    unsigned char num_locals;
    int export_off;
    unsigned char export_len;
};

struct wst {
    unsigned int op[64];
    unsigned int loc[16];
    int lpc[16];
    int lsp[16];
    unsigned char lkind[16];
};

int check_magic(void);

void parse_module(struct wmod *m);

int scan_end(int pc);

unsigned int invoke(struct wst *st, struct wmod *m, unsigned int a, unsigned int b);
