// This file is generated by ATC.

#include "smoke4.h"

int get_num(struct modu *m) {
    return m->num;
}

unsigned char get_byte(int i, struct modu *m) {
    return m->bytes[i];
}

void set_num(int v, struct modu *m) {
    m->num = v;
}
