// This file is generated by ATC.

struct modu {
    int num;
    unsigned char bytes[16];
};

int get_num(struct modu *m);

unsigned char get_byte(int i, struct modu *m);

void set_num(int v, struct modu *m);
