// This file is generated by ATC.

extern unsigned char wasm_buf[65536];

struct wmod {
    unsigned char err;
    unsigned int body_off;
    unsigned int body_len;
    unsigned char num_params;
    unsigned char num_results;
    unsigned char num_locals;
    unsigned int export_off;
    unsigned char export_len;
};

int check_magic(void);

void parse_header(struct wmod *m);

unsigned int invoke(struct wmod *m, unsigned int a, unsigned int b);
