// This file is generated by ATC.

#include "wasm-vm1.h"

unsigned char wasm_buf[65536];

int check_magic(void) {
    return (int) wasm_buf[0] == 0 && (int) wasm_buf[1] == 97 && (int) wasm_buf[2] == 115 && (int) wasm_buf[3] == 109;
}

void parse_header(struct wmod *m) {
    int ok = check_magic();
    if (ok) {
        m->err = (unsigned char) 0;
    } else {
        m->err = (unsigned char) 1;
    }
}

unsigned int invoke(struct wmod *m, unsigned int a, unsigned int b) {
    return a + b;
}
